// FONT AWESOME
import { dom, library } from '@fortawesome/fontawesome-svg-core';
import {
  faAtlas,
  faBook as falFaBook, faBookHeart, faBookmark, faBooks,
  faCalendar,
  faCoffeeTogo,
  faCommentLines,
  faComments,
  faCut,
  faFeather, faFileAlt,
  faFingerprint,
  faFlag,
  faGift,
  faGraduationCap, faGrimace,
  faHatChef,
  faHeadSideBrain, faHeart, faHistory, faKissWinkHeart, faLaughBeam,
  faLightbulb,
  faMapMarked,
  faMugHot,
  faMusic,
  faPaintBrush,
  faPaperPlane,
  faPencil,
  faPencilPaintbrush,
  faPray,
  faPrayingHands,
  faPuzzlePiece,
  faQuestion, faQuoteRight,
  faRecordVinyl,
  faScrollOld,
  faSmile,
  faStarExclamation,
  faStars, faSurprise,
  faSwords, faTheaterMasks,
  faUfo, faUser, faUserSecret,
  faWandMagic,
} from '@fortawesome/pro-light-svg-icons';

import { faBook as fasFaBook } from '@fortawesome/pro-solid-svg-icons';

library.add(
  falFaBook,
  fasFaBook,
  faLightbulb,
  faSmile,
  faHeadSideBrain,
  faHatChef,
  faGraduationCap,
  faMapMarked,
  faFlag,
  faSwords,
  faStars,
  faAtlas,
  faQuestion,
  faPencilPaintbrush,
  faGift,
  faCoffeeTogo,
  faMusic,
  faRecordVinyl,
  faCalendar,
  faMugHot,
  faPrayingHands,
  faPray,
  faPuzzlePiece,
  faPaperPlane,
  faCut,
  faPencil,
  faPaintBrush,
  faStarExclamation,
  faComments,
  faCommentLines,
  faUfo,
  faWandMagic,
  faFingerprint,
  faScrollOld,
  faFeather,
  faBooks,
  faBookHeart,
  faGrimace,
  faSurprise,
  faHistory,
  faLaughBeam,
  faBookmark,
  faUser,
  faMapMarked,
  faFileAlt,
  faUserSecret,
  faHeart,
  faKissWinkHeart,
  faTheaterMasks,
  faQuoteRight
);

dom.watch();
