# This is master branch pipeline which:
# 1. Install project dependencies
# 2. Run build script
# 3. Set remote url for git access (you need to specify `ACCESS_TOKEN` variable
# in repository enviroment variables)
# 4. Execute push-to-build.sh bash script wich pushes contents of build to `build` branch
image: node:6.10.0
pipelines:
  branches:
    master:
      - step:
          script: # Modify the commands below to build your repository.
            - curl -o- -L https://yarnpkg.com/install.sh | bash -s
            - export PATH=$HOME/.yarn/bin:$PATH
            - yarn global add gulp-cli
            - yarn
            - gulp build
            - git remote set-url origin https://x-token-auth:${ACCESS_TOKEN}@bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}.git
            - bash push-to-build.sh