name: CI

on:
  push:
    branches: [master, main, build/**, feature/**]
  pull_request:
    branches: [master, main]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Set up .npmrc for FontAwesome private registry
        run: |
          echo "@awesome.me:registry=https://npm.fontawesome.com/" >> .npmrc
          echo "@fortawesome:registry=https://npm.fontawesome.com/" >> .npmrc
          echo "//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_NPM_TOKEN }}" >> .npmrc

      - name: Install dependencies
        run: |
          corepack enable || true
          yarn install --frozen-lockfile

      - name: Lint
        run: |
          yarn lint

      - name: Build
        run: |
          yarn build
